# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Swift Activities CI

on:
  push:
    paths:
      - swift-activities/**
      - .github/workflows/swift_activities.yml
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5434:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Copy application.properties
      working-directory: swift-activities
      run: cp src/main/resources/application.properties.example src/main/resources/application.properties
    - name: Grant execute permission for gradlew
      working-directory: swift-activities
      run: chmod +x ./gradlew
    - name: Run Tests
      working-directory: swift-activities
      run: ./gradlew clean test
    - name: Run app in bg
      working-directory: swift-activities
      run: ./gradlew bootRun &
    - name: Wait for the application to start
      run: sleep 20
    - name: Check the health check URL
      run: curl -sSf http://localhost:8080/api/health-check
